services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mall
      POSTGRES_USER: mall
      POSTGRES_PASSWORD: mall
    ports:
      - "5432:5432"
    volumes:
      - mall_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  mall_pg_data:
